### ISSUE TITLE
Undefined array key "p24_order_id"

### ISSUE THREAD

**Issue by kaftom** [mnastalski/przelewy24-php#1]
I have an error while payment

`ErrorException
Undefined array key "p24_order_id"`

Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
...\vendor\mnastalski\przelewy24-php\src\TransactionStatusNotification.php:49

```
    /**
    * @return int
    */
    public function orderId(): int
    {
        return $this->parameters['p24_order_id'];             // <-- error
    }
```

my code is like in your example:

```
$przelewy24 = new Przelewy24([
                        'merchant_id' => $merchantId,
                         'crc'         => $crc,     
                         'live'        => false, 
                         ]);


$transaction = $przelewy24->transaction([
                        'session_id'  => $sessionId,
                        'url_return'  => $urlReturn,
                        'url_status'  => '',
                         'amount'      => $amount,
                         'description' => $description,
                         'email'       => $customer_email,
                         ]);

$transaction->token();

$transaction->redirectUrl();

$webhook = $przelewy24->handleWebhook();

$przelewy24->verify([
                        'session_id' => $sessionId,
                        'order_id'   => $webhook->orderId(),    
                        'amount'     => $amount,
                    ]);

```
And by the way: is it possible to choose a currency in your code?

**Comment by mnastalski** [comment]
Are you getting the error when Przelewy24 sends a status request to your server? You can also dump the whole request in the controller to see what was sent to you.

> And by the way: is it possible to choose a currency in your code?

Yes, you can pass any parameters that are accepted by Przelewy24 to the `transaction()` method, e.g.:

```php
$transaction = $przelewy24->transaction([
    'session_id' => 'unique order identifier from your application',
    'url_return' => 'url to return to post transaction',
    'url_status' => 'url to which the transaction status webhook will be sent',
    'amount' => 'transaction amount as an integer (1.25 PLN = 125)',
    'description' => 'transaction description',
    'email' => 'buyer email address',
    'currency' => 'PLN',
    'language' => Transaction::LANGUAGE_PL,
    ...
]);
```

**Comment by kaftom** [comment]
Ok, i checked what is result of $webhook. Laravel saying:
`dd($webhook);`

    Przelewy24\TransactionStatusNotification {#1559 ▼
          -parameters: []
    }

As you can see there is an empty array. Any others variables are ok:

`$przelewy24`

    Przelewy24\Przelewy24 {#1306 ▼
      -config: Przelewy24\Config {#1554 ▶}
      -api: Przelewy24\Api\Api {#1559 ▼
      -config: Przelewy24\Config {#1554 ▼
      -merchantId: 12*****                                             // <-- there is number but now i just remove it
      -posId: 12*****
      -crc: "a9b5*************"
      -isLiveMode: false
    }
    -client: GuzzleHttp\Client {#1555 ▼
      -config: array:9 [▼
        "base_uri" => GuzzleHttp\Psr7\Uri {#1573 ▼
          -scheme: "https"
          -userInfo: ""
          -host: "sandbox.przelewy24.pl"
          -port: null
          -path: "/"
          -query: ""
          -fragment: ""
        }
        "handler" => GuzzleHttp\HandlerStack {#1557 ▼
          -handler: Closure(RequestInterface $request, array $options): PromiseInterface {#1568 ▶}
          -stack: array:4 [▼
            0 => array:2 [▼
              0 => Closure(callable $handler): callable {#1569 ▼
                returnType: "callable"
                class: "GuzzleHttp\Middleware"
                use: {▼
                  $bodySummarizer: null
                }
                file: "C:\Users\...\vendor\guzzlehttp\guzzle\src\Middleware.php"
                line: "58 to 73"
              }
              1 => "http_errors"
            ]
            1 => array:2 [▼
              0 => Closure(callable $handler): RedirectMiddleware {#1570 ▼
                returnType: "GuzzleHttp\RedirectMiddleware"
                class: "GuzzleHttp\Middleware"
                file: "C:\Users\...\vendor\guzzlehttp\guzzle\src\Middleware.php"
                line: "153 to 155"
              }
              1 => "allow_redirects"
            ]
            2 => array:2 [▼
              0 => Closure(callable $handler): callable {#1571 ▼
                returnType: "callable"
                class: "GuzzleHttp\Middleware"
                file: "C:\Users\...\vendor\guzzlehttp\guzzle\src\Middleware.php"
                line: "28 to 45"
              }
              1 => "cookies"
            ]
            3 => array:2 [▼
              0 => Closure(callable $handler): PrepareBodyMiddleware {#1572 ▼
                returnType: "GuzzleHttp\PrepareBodyMiddleware"
                class: "GuzzleHttp\Middleware"
                file: "C:\Users\...\vendor\guzzlehttp\guzzle\src\Middleware.php"
                line: "224 to 226"
              }
              1 => "prepare_body"
            ]
          ]
          -cached: Closure($request, array $options) {#1581 ▼
            class: "GuzzleHttp\Middleware"
            use: {▶}
            file: "C:\Users\...\vendor\guzzlehttp\guzzle\src\Middleware.php"
            line: "59 to 72"
          }
        }
        "allow_redirects" => array:5 [▼
          "max" => 5
          "protocols" => array:2 [▼
            0 => "http"
            1 => "https"
          ]
          "strict" => false
          "referer" => false
          "track_redirects" => false
        ]
        "http_errors" => true
        "decode_content" => true
        "verify" => true
        "cookies" => false
        "idn_conversion" => false
        "headers" => array:1 [▼
          "User-Agent" => "GuzzleHttp/7"
        ]
      ]
    }
  }
}
    

`$transaction`:

    Przelewy24\Api\Response\RegisterTransactionResponse {#1561 ▼
      #token: "BE******71-******-******-2A******05"                               // <-- there is number but now i just remove it
      -gatewayUrl: "https://sandbox.przelewy24.pl/trnRequest"
      #error: "0"
      #errorMessage: null
    }

So, only webhook is empty.

**Comment by mnastalski** [comment]
How are you getting `dd()` of `$webhook` if it's the request from przelewy24 that should be executing it and not you? You need a POST endpoint (URL is set in `url_status` param in `$przelewy24->transaction()`) which will only run `$webhook = $przelewy24->handleWebhook();` and `$przelewy24->verify()`.

https://developers.przelewy24.pl/index.php?pl#tag/Notification (the docs are for a newer version and are slightly different)
