### ISSUE TITLE
Question regarding additional parameters on transaction 

### ISSUE THREAD

**Issue by inprogra** [mnastalski/przelewy24-php#2]
Hi,

While creating transaction with Yours composer library I am in need to pass argument 'waitForResult' => true.

However because it doesnt work as described on przelewy24 docs I started to wonder if from transaction data that I am passing inside I am using proper parameters.

In docs there is sessionId and here I am passing session_id. Maybe the same should be with "waitForResult" parameter?

  $transaction = $payment->transaction([
                        'session_id' => $order_name,
                        'url_return' => ''
                        'url_status' => '',
                        'waitForResult' => true,
                        'amount' => '',
                        'description' => '',
                        'email' => '',
                    ]);

Regards
Łukasz

**Comment by mnastalski** [comment]
Yeah, all parameters should be passed in `snake_case`, so `wait_for_result => true` should do it.
