### ISSUE TITLE
Transaction verification issue

### ISSUE THREAD

**Issue by modwebpl** [mnastalski/przelewy24-php#3]
Hello,

Thanks for native PHP module but It seems there is an error during transaction verification waiting for Przelewy24 incoming request.

In transaction "url_status" i set url with php code:

$webhook = $przelewy24->handleWebhook(); <-- but this doesnt return any parameters or objects

$przelewy24->verify([
    'session_id' => '12343', // my test order_id
    'order_id' => $webhook->orderId(),   // <-- for some reason $webhook is null :/
    'amount' => 'transaction amount as an integer (1.25 PLN = 125)',
]);

Method "$przelewy24->verify" throw error cause $webhook is null.

**Comment by lukaszwronskicom** [comment]
Hello,

I hope that you resolved the problem :)

I will try to provide some information that helped me create the verification script.

1. Przelewy24 runs the script 'url_status' **only when payment** was accept. When payment wasn't accepted, API not run this script. It always runs in the background. You cannot **run this script from your browser**.

2. I propose **FOR TESTS** use this:

```
$przelewy24 = new Przelewy24([
            'merchant_id' => 'm_id',
            'crc' => 'crc',
            'live' => false,
]);

$webhook = $przelewy24->handleWebhook();

$res = $przelewy24->verify([
            'session_id' => $webhook->sessionId(),
            'order_id' => $webhook->orderId(),
            'amount' => $webhook->amount(),
]);

ob_flush();
ob_start();
var_dump($webhook);
var_dump($webhook->sessionId()); //will return an ID order
var_dump($webhook->amount()); //will return an amount
var_dump($res); //will return response without errors:)
file_put_contents("dump.txt", ob_get_flush());


```

Create a new payment **with a new ID**. When the user "pays" for the order, the script will throw you what you need to the dump.txt file.

If the user does not make the payment, the above file will not be launched.

If I made a mistake somewhere - sorry :)
