### ISSUE TITLE
Błąd p24_api_version:Incorrect api version

### ISSUE THREAD

**Issue by kkraszy** [mnastalski/przelewy24-php#4]
Hej,
Biblioteka na niektórych serwerach przekazuje  pole p24_api_version  jako float 3,2  (z przecinkiem) i przelewy24 zwracają p24_api_version:Incorrect api version.
Sugeruje numer wersji  API trzymać jako string '3.2' - to  rozwiąże problem.

**Comment by mnastalski** [comment]
Cześć,
Poprawione w v0.0.3

Dzięki 👍
