### ISSUE TITLE
Weryfikacja transakcji

### ISSUE THREAD

**Issue by wujekpiotr** [mnastalski/przelewy24-php#5]
Witam. Jak sprawdzić czy weryfikacja transakcji przebiegła pomyślnie? Gdyby ApiResponse::hasError była metodą publiczną możnaby jej użyć do weryfikacji:

```
$verified = $p24->verify([
                'session_id' => $order->getSessionId(), //unique order identifier from your application
                'order_id' => $webhook->orderId(),  // przelewy24 order id
                'amount' => round($order->getTotalSum() * 100), //transaction amount as an integer (1.25 PLN = 125)
            ]);
if (!$verified->hasError()) {
//$order->setAsPaid(); etc...
}
```
... ale metoda hasError jest chroniona. Może jest jakiś inny sposób?

**Comment by mnastalski** [comment]
Cześć, jeśli będzie jakiś error w zwrotce (czyli właśnie spełni się `hasError()`) to skrypt wyrzuci `Przelewy24\Exceptions\ApiResponseException` (które jest przedłużeniem `Przelewy24\Exceptions\ApiResponseException\Przelewy24Exception`) i można go ewentualnie zgarnąć try/catchem:

```php
try {
    $verified = $p24->verify([
        ...
    ]);
} catch (Przelewy24Exception $e) {
    ...
}
```

Jeśli przejdzie poprawnie to po prostu nic nie rzuca
